version: "3.4"

networks:
  virtual_net:
    driver: overlay
  
services:
  webAPI:
    image: "netcore-monitoring"
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://*:80
    networks: 
      - virtual_net
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - webAPI
    networks:
      - virtual_net
  
  grafana:
    image: grafana/grafana
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    volumes:
        - ./grafana/data/:/var/lib/grafana
        - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
        - ./grafana_config/grafana.config
    networks:
        - virtual_net